package completabletest;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

/**
 * CompletableFuture的handle方法表示，某个任务执行完成后，执行回调方法，并且是有返回值的;
 * 并且handle方法返回的CompletableFuture的result是回调方法执行的结果。
 *
 * @author dingyawu
 * @version 1.0
 * @date created in 2021-07-05 17:40
 */
public class FutureHandlerTest {
  public static void main(String[] args) throws ExecutionException, InterruptedException {

    CompletableFuture<String> orgFuture =
        CompletableFuture.supplyAsync(
            () -> {
              System.out.println("当前线程名称：" + Thread.currentThread().getName());
              try {
                Thread.sleep(2000L);
              } catch (InterruptedException e) {
                e.printStackTrace();
              }
              return "捡田螺的小男孩";
            });

    CompletableFuture<String> rstFuture =
        orgFuture.handle(
            (a, throwable) -> {
              System.out.println("上个任务执行完啦，还把" + a + "传过来");
              if ("捡田螺的小男孩".equals(a)) {
                System.out.println("666");
                return "关注了";
              }
              System.out.println("233333");
              return null;
            });

    System.out.println(rstFuture.get());
  }
}
